version: "3.8"
services:
  sources-sk:
    build:
      context: .
      target: dev
    env_file: .env
    networks:
      - elasticsearch
      - sources
    restart: on-failure
    volumes:
      - ./.rubocop.yml:/home/x/r/.rubocop.yml
      - ./bin:/home/x/r/bin
      - ./Gemfile.lock:/home/x/r/Gemfile.lock
      - ./Gemfile:/home/x/r/Gemfile
      - ./lib:/home/x/r/lib
      - ./register_sources_sk.gemspec:/home/x/r/register_sources_sk.gemspec
      - ./spec:/home/x/r/spec
networks:
  elasticsearch: {}
  sources: {}
